# k8s/postgres.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
spec:
  instances: 2
  # k3d uses the 'local-path' storage class by default
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
